[
    {
        "type": "LINE_NUMBER",
        "lexeme": "10",
        "line": 1,
        "col": 1,
        "value": 10
    },
    {
        "type": "COMMENT",
        "lexeme": "REBOTES, por Alexander Martin",
        "line": 1,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 1,
        "col": 34,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "20",
        "line": 2,
        "col": 1,
        "value": 20
    },
    {
        "type": "COMMENT",
        "lexeme": "copyright (c) AMSOFT 1984",
        "line": 2,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 2,
        "col": 30,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "30",
        "line": 3,
        "col": 1,
        "value": 30
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 3,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 3,
        "col": 5,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "40",
        "line": 4,
        "col": 1,
        "value": 40
    },
    {
        "type": "KEYWORD",
        "lexeme": "MODE",
        "line": 4,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 4,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "BORDER",
        "line": 4,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 4,
        "col": 18,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 19,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 20,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 4,
        "col": 24,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 25,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 4,
        "col": 26,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 27,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 4,
        "col": 32,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 33,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "26",
        "line": 4,
        "col": 34,
        "value": 26
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 36,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 37,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 4,
        "col": 41,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 42,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 4,
        "col": 43,
        "value": 24
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 45,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 46,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 4,
        "col": 50,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 51,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "6",
        "line": 4,
        "col": 52,
        "value": 6
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 4,
        "col": 53,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "50",
        "line": 5,
        "col": 1,
        "value": 50
    },
    {
        "type": "KEYWORD",
        "lexeme": "SPEED KEY",
        "line": 5,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 5,
        "col": 14,
        "value": 15
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 5,
        "col": 17,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 5,
        "col": 18,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "60",
        "line": 6,
        "col": 1,
        "value": 60
    },
    {
        "type": "KEYWORD",
        "lexeme": "ENV",
        "line": 6,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 6,
        "col": 8,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 6,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 6,
        "col": 10,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 6,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "18",
        "line": 6,
        "col": 12,
        "value": 18
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 6,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 6,
        "col": 15,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 6,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "11",
        "line": 6,
        "col": 17,
        "value": 11
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 6,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 6,
        "col": 20,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 6,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 6,
        "col": 22,
        "value": 10
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 6,
        "col": 24,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "70",
        "line": 7,
        "col": 1,
        "value": 70
    },
    {
        "type": "KEYWORD",
        "lexeme": "ENT",
        "line": 7,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 7,
        "col": 8,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 7,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 7,
        "col": 10,
        "value": 10
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 7,
        "col": 12,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 7,
        "col": 13,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 7,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 7,
        "col": 15,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 7,
        "col": 16,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "80",
        "line": 8,
        "col": 1,
        "value": 80
    },
    {
        "type": "KEYWORD",
        "lexeme": "ENV",
        "line": 8,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 8,
        "col": 8,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 8,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 8,
        "col": 10,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 8,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 8,
        "col": 12,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 8,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 8,
        "col": 14,
        "value": 16
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 8,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 8,
        "col": 17,
        "value": 5
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 8,
        "col": 18,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 8,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 8,
        "col": 20,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 8,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 8,
        "col": 22,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 8,
        "col": 23,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "90",
        "line": 9,
        "col": 1,
        "value": 90
    },
    {
        "type": "KEYWORD",
        "lexeme": "ENV",
        "line": 9,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 9,
        "col": 8,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 9,
        "col": 10,
        "value": 5
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 9,
        "col": 12,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 9,
        "col": 14,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 15,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 9,
        "col": 16,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 17,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 9,
        "col": 18,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "21",
        "line": 9,
        "col": 19,
        "value": 21
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "22",
        "line": 9,
        "col": 22,
        "value": 22
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 24,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "9",
        "line": 9,
        "col": 25,
        "value": 9
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 26,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 9,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 9,
        "col": 28,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 29,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 9,
        "col": 30,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 9,
        "col": 31,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "100",
        "line": 10,
        "col": 1,
        "value": 100
    },
    {
        "type": "KEYWORD",
        "lexeme": "ENT",
        "line": 10,
        "col": 5,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 10,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 10,
        "col": 10,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 10,
        "col": 12,
        "value": 10
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 10,
        "col": 15,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 10,
        "col": 17,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 18,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 10,
        "col": 19,
        "value": 5
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 20,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 10,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "7",
        "line": 10,
        "col": 22,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 10,
        "col": 24,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 25,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 10,
        "col": 26,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "11",
        "line": 10,
        "col": 28,
        "value": 11
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 10,
        "col": 31,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 10,
        "col": 33,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 34,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 10,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 10,
        "col": 36,
        "value": 4
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 10,
        "col": 37,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 10,
        "col": 38,
        "value": 8
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 10,
        "col": 39,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "110",
        "line": 11,
        "col": 1,
        "value": 110
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 11,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 11,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "120",
        "line": 12,
        "col": 1,
        "value": 120
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 12,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 12,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "130",
        "line": 13,
        "col": 1,
        "value": 130
    },
    {
        "type": "KEYWORD",
        "lexeme": "MOVE",
        "line": 13,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "30",
        "line": 13,
        "col": 10,
        "value": 30
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 13,
        "col": 12,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 13,
        "col": 13,
        "value": 32
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 13,
        "col": 15,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "DRAWR",
        "line": 13,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 13,
        "col": 22,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 13,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "400",
        "line": 13,
        "col": 24,
        "value": 400
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 13,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 13,
        "col": 28,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 13,
        "col": 29,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "MOVE",
        "line": 13,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "610",
        "line": 13,
        "col": 35,
        "value": 610
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 13,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 13,
        "col": 39,
        "value": 32
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 13,
        "col": 41,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "DRAWR",
        "line": 13,
        "col": 42,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 13,
        "col": 48,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 13,
        "col": 49,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "400",
        "line": 13,
        "col": 50,
        "value": 400
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 13,
        "col": 53,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 13,
        "col": 54,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 13,
        "col": 55,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "140",
        "line": 14,
        "col": 1,
        "value": 140
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 14,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 14,
        "col": 9,
        "value": 3
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 14,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 14,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 14,
        "col": 18,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 14,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 14,
        "col": 20,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 14,
        "col": 21,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 14,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "STRING$",
        "line": 14,
        "col": 28,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 14,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "36",
        "line": 14,
        "col": 36,
        "value": 36
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 14,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "143",
        "line": 14,
        "col": 39,
        "value": 143
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 14,
        "col": 42,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 14,
        "col": 43,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "150",
        "line": 15,
        "col": 1,
        "value": 150
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 15,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 15,
        "col": 9,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 15,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 15,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 15,
        "col": 18,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 15,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 15,
        "col": 20,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 15,
        "col": 21,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 15,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "STRING$",
        "line": 15,
        "col": 28,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 15,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "36",
        "line": 15,
        "col": 36,
        "value": 36
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 15,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "143",
        "line": 15,
        "col": 39,
        "value": 143
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 15,
        "col": 42,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 15,
        "col": 43,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "160",
        "line": 16,
        "col": 1,
        "value": 160
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 16,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 16,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 16,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 16,
        "col": 11,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "r",
        "line": 16,
        "col": 15,
        "value": "R"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 16,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 16,
        "col": 17,
        "value": 5
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 16,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "6",
        "line": 16,
        "col": 22,
        "value": 6
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 16,
        "col": 23,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 16,
        "col": 24,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 16,
        "col": 31,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 16,
        "col": 32,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "r",
        "line": 16,
        "col": 33,
        "value": "R"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 16,
        "col": 34,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 16,
        "col": 35,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "STRING$",
        "line": 16,
        "col": 41,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 16,
        "col": 48,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "36",
        "line": 16,
        "col": 49,
        "value": 36
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 16,
        "col": 51,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "143",
        "line": 16,
        "col": 52,
        "value": 143
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 16,
        "col": 55,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 16,
        "col": 56,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 16,
        "col": 57,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "r",
        "line": 16,
        "col": 62,
        "value": "R"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 16,
        "col": 63,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "170",
        "line": 17,
        "col": 1,
        "value": 170
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 17,
        "col": 5,
        "value": "BX"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 17,
        "col": 7,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "9",
        "line": 17,
        "col": 8,
        "value": 9
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 17,
        "col": 9,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "180",
        "line": 18,
        "col": 1,
        "value": 180
    },
    {
        "type": "IDENT",
        "lexeme": "pelotas",
        "line": 18,
        "col": 5,
        "value": "PELOTAS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 18,
        "col": 12,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 18,
        "col": 13,
        "value": 5
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 18,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 18,
        "col": 15,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 18,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 18,
        "col": 22,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 18,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maximo",
        "line": 18,
        "col": 24,
        "value": "MAXIMO"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 18,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 18,
        "col": 31,
        "value": 0
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 18,
        "col": 32,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "190",
        "line": 19,
        "col": 1,
        "value": 190
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 19,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 19,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 19,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 19,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "680",
        "line": 19,
        "col": 17,
        "value": 680
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 19,
        "col": 20,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "200",
        "line": 20,
        "col": 1,
        "value": 200
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 20,
        "col": 5,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY$",
        "line": 20,
        "col": 8,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "<>",
        "line": 20,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 20,
        "col": 16,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 20,
        "col": 20,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 20,
        "col": 21,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 20,
        "col": 23,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 20,
        "col": 25,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "JOY",
        "line": 20,
        "col": 29,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 20,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 20,
        "col": 33,
        "value": 0
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 20,
        "col": 34,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 20,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 20,
        "col": 36,
        "value": 16
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 20,
        "col": 39,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "200",
        "line": 20,
        "col": 44,
        "value": 200
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 20,
        "col": 47,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "210",
        "line": 21,
        "col": 1,
        "value": 210
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 21,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 21,
        "col": 12,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 21,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "23",
        "line": 21,
        "col": 14,
        "value": 23
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 21,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 21,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SPACE$",
        "line": 21,
        "col": 23,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 21,
        "col": 29,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "36",
        "line": 21,
        "col": 30,
        "value": 36
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 21,
        "col": 32,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 21,
        "col": 33,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 21,
        "col": 34,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 21,
        "col": 41,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 21,
        "col": 42,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 21,
        "col": 43,
        "value": 24
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 21,
        "col": 45,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 21,
        "col": 46,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SPACE$",
        "line": 21,
        "col": 52,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 21,
        "col": 58,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "40",
        "line": 21,
        "col": 59,
        "value": 40
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 21,
        "col": 61,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 21,
        "col": 62,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 21,
        "col": 63,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "220",
        "line": 22,
        "col": 1,
        "value": 220
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 22,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "690",
        "line": 22,
        "col": 11,
        "value": 690
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 22,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 22,
        "col": 15,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "660",
        "line": 22,
        "col": 21,
        "value": 660
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 22,
        "col": 24,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 22,
        "col": 25,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "280",
        "line": 22,
        "col": 30,
        "value": 280
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 22,
        "col": 33,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "230",
        "line": 23,
        "col": 1,
        "value": 230
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 23,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 23,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "240",
        "line": 24,
        "col": 1,
        "value": 240
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 24,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 24,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "250",
        "line": 25,
        "col": 1,
        "value": 250
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 25,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 25,
        "col": 12,
        "value": "BX"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 25,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 25,
        "col": 15,
        "value": 24
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 25,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 25,
        "col": 18,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"  \"",
        "line": 25,
        "col": 23,
        "value": "  "
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 25,
        "col": 27,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "STRING$",
        "line": 25,
        "col": 28,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 25,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 25,
        "col": 36,
        "value": 4
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 25,
        "col": 37,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "131",
        "line": 25,
        "col": 38,
        "value": 131
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 25,
        "col": 41,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 25,
        "col": 42,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"  \"",
        "line": 25,
        "col": 43,
        "value": "  "
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 25,
        "col": 47,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 25,
        "col": 48,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 25,
        "col": 54,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "260",
        "line": 26,
        "col": 1,
        "value": 260
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 26,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 26,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "270",
        "line": 27,
        "col": 1,
        "value": 270
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 27,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 27,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "280",
        "line": 28,
        "col": 1,
        "value": 280
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 28,
        "col": 5,
        "value": "XA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 28,
        "col": 7,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 28,
        "col": 8,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 28,
        "col": 9,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 28,
        "col": 10,
        "value": "YA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 28,
        "col": 12,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 28,
        "col": 13,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 28,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 28,
        "col": 15,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INT",
        "line": 28,
        "col": 18,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 28,
        "col": 21,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RND",
        "line": 28,
        "col": 22,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 28,
        "col": 25,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 28,
        "col": 26,
        "value": 2
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 28,
        "col": 27,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 28,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 28,
        "col": 29,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 28,
        "col": 31,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 28,
        "col": 36,
        "value": "XA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 28,
        "col": 38,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 28,
        "col": 39,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 28,
        "col": 40,
        "value": "XA"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 28,
        "col": 42,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "290",
        "line": 29,
        "col": 1,
        "value": 290
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 29,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 29,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 29,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 29,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "250",
        "line": 29,
        "col": 17,
        "value": 250
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 29,
        "col": 20,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "300",
        "line": 30,
        "col": 1,
        "value": 300
    },
    {
        "type": "KEYWORD",
        "lexeme": "ORIGIN",
        "line": 30,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 30,
        "col": 12,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 30,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "400",
        "line": 30,
        "col": 14,
        "value": 400
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 30,
        "col": 17,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "310",
        "line": 31,
        "col": 1,
        "value": 310
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 31,
        "col": 5,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 31,
        "col": 6,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 31,
        "col": 7,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 31,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 31,
        "col": 10,
        "value": 4
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 31,
        "col": 11,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 31,
        "col": 12,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 31,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "11",
        "line": 31,
        "col": 14,
        "value": 11
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 31,
        "col": 16,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 31,
        "col": 17,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 31,
        "col": 19,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 31,
        "col": 20,
        "value": "X"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 31,
        "col": 21,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 31,
        "col": 22,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 31,
        "col": 24,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 31,
        "col": 25,
        "value": "Y"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 31,
        "col": 26,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "320",
        "line": 32,
        "col": 1,
        "value": 320
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 32,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 32,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "330",
        "line": 33,
        "col": 1,
        "value": 330
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 33,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 33,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "340",
        "line": 34,
        "col": 1,
        "value": 340
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 34,
        "col": 5,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 34,
        "col": 7,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 34,
        "col": 8,
        "value": "X"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 34,
        "col": 9,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 34,
        "col": 10,
        "value": "XA"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 34,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 34,
        "col": 13,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 34,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 34,
        "col": 16,
        "value": "Y"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 34,
        "col": 17,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 34,
        "col": 18,
        "value": "YA"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 34,
        "col": 20,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "350",
        "line": 35,
        "col": 1,
        "value": 350
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 35,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 35,
        "col": 8,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 35,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 35,
        "col": 11,
        "value": 3
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 35,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 35,
        "col": 16,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 35,
        "col": 18,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "38",
        "line": 35,
        "col": 19,
        "value": 38
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 35,
        "col": 22,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 35,
        "col": 27,
        "value": "XA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 35,
        "col": 29,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 35,
        "col": 30,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 35,
        "col": 31,
        "value": "XA"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 35,
        "col": 33,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "360",
        "line": 36,
        "col": 1,
        "value": 360
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 36,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "540",
        "line": 36,
        "col": 11,
        "value": 540
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 36,
        "col": 14,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "370",
        "line": 37,
        "col": 1,
        "value": 370
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 37,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 37,
        "col": 8,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 37,
        "col": 11,
        "value": 24
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 37,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 37,
        "col": 18,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 37,
        "col": 20,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 37,
        "col": 21,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 37,
        "col": 24,
        "value": 1
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 37,
        "col": 26,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 37,
        "col": 30,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 37,
        "col": 32,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 37,
        "col": 33,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "6",
        "line": 37,
        "col": 36,
        "value": 6
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 37,
        "col": 38,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 37,
        "col": 43,
        "value": "YA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 45,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 37,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 37,
        "col": 47,
        "value": "YA"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 49,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 37,
        "col": 50,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 52,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 37,
        "col": 53,
        "value": "Y1"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 37,
        "col": 55,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 37,
        "col": 56,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 57,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 37,
        "col": 58,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "130",
        "line": 37,
        "col": 64,
        "value": 130
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 37,
        "col": 67,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "44",
        "line": 37,
        "col": 68,
        "value": 44
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 37,
        "col": 70,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 37,
        "col": 71,
        "value": 8
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 37,
        "col": 72,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "7",
        "line": 37,
        "col": 73,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 37,
        "col": 74,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 37,
        "col": 75,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 37,
        "col": 76,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 37,
        "col": 77,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 78,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 37,
        "col": 79,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 80,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 37,
        "col": 81,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 37,
        "col": 82,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 37,
        "col": 83,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 37,
        "col": 84,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 37,
        "col": 85,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 87,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 37,
        "col": 88,
        "value": 5
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 37,
        "col": 89,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 37,
        "col": 91,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 37,
        "col": 94,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 37,
        "col": 95,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 37,
        "col": 96,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 37,
        "col": 97,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 99,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 37,
        "col": 100,
        "value": 2
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 37,
        "col": 101,
        "value": null
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 37,
        "col": 102,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 103,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 37,
        "col": 104,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 37,
        "col": 107,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 108,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 37,
        "col": 109,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 37,
        "col": 110,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 37,
        "col": 112,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 37,
        "col": 117,
        "value": "XA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 119,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 37,
        "col": 120,
        "value": "XA"
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 37,
        "col": 122,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 37,
        "col": 123,
        "value": "A"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 124,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 37,
        "col": 125,
        "value": "X1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 127,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 37,
        "col": 128,
        "value": "X1"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 130,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xa",
        "line": 37,
        "col": 131,
        "value": "XA"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 133,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 37,
        "col": 134,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 136,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 37,
        "col": 137,
        "value": "Y1"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 139,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 37,
        "col": 140,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 37,
        "col": 141,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "380",
        "line": 38,
        "col": 1,
        "value": 380
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 38,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 38,
        "col": 8,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 38,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 38,
        "col": 10,
        "value": 25
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 38,
        "col": 13,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 38,
        "col": 18,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 38,
        "col": 25,
        "value": "X"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 38,
        "col": 26,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 38,
        "col": 27,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 38,
        "col": 28,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 38,
        "col": 29,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 38,
        "col": 34,
        "value": " "
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 38,
        "col": 37,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 38,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "500",
        "line": 38,
        "col": 43,
        "value": 500
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 38,
        "col": 46,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "390",
        "line": 39,
        "col": 1,
        "value": 390
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 39,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "250",
        "line": 39,
        "col": 11,
        "value": 250
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 39,
        "col": 14,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "400",
        "line": 40,
        "col": 1,
        "value": 400
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 40,
        "col": 5,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 40,
        "col": 6,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "TEST",
        "line": 40,
        "col": 7,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 40,
        "col": 11,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 40,
        "col": 12,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 40,
        "col": 13,
        "value": 16
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 40,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 40,
        "col": 16,
        "value": "X1"
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 40,
        "col": 18,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 40,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 40,
        "col": 20,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 40,
        "col": 21,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 40,
        "col": 22,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 40,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 40,
        "col": 24,
        "value": 16
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 40,
        "col": 26,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 40,
        "col": 27,
        "value": "Y1"
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 40,
        "col": 29,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 40,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 40,
        "col": 31,
        "value": 1
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 40,
        "col": 32,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 40,
        "col": 33,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "410",
        "line": 41,
        "col": 1,
        "value": 410
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 41,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 41,
        "col": 8,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "<>",
        "line": 41,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 41,
        "col": 11,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 41,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 41,
        "col": 18,
        "value": "YA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 41,
        "col": 20,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 41,
        "col": 21,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 41,
        "col": 22,
        "value": "YA"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 41,
        "col": 24,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xz",
        "line": 41,
        "col": 25,
        "value": "XZ"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 41,
        "col": 27,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 41,
        "col": 28,
        "value": "X1"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 41,
        "col": 30,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "yz",
        "line": 41,
        "col": 31,
        "value": "YZ"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 41,
        "col": 33,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 41,
        "col": 34,
        "value": "Y1"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 41,
        "col": 36,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 41,
        "col": 37,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 41,
        "col": 39,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 41,
        "col": 40,
        "value": "Y1"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 41,
        "col": 42,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 41,
        "col": 43,
        "value": "YA"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 41,
        "col": 45,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 41,
        "col": 46,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "590",
        "line": 41,
        "col": 52,
        "value": 590
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 41,
        "col": 55,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 41,
        "col": 56,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 41,
        "col": 59,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 41,
        "col": 60,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 41,
        "col": 61,
        "value": 2
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 41,
        "col": 63,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 41,
        "col": 68,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 41,
        "col": 74,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 41,
        "col": 75,
        "value": "PUNTOS"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 41,
        "col": 81,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 41,
        "col": 82,
        "value": 10
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 41,
        "col": 84,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 41,
        "col": 85,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "660",
        "line": 41,
        "col": 91,
        "value": 660
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 41,
        "col": 94,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "420",
        "line": 42,
        "col": 1,
        "value": 420
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 42,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 42,
        "col": 8,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 42,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 42,
        "col": 10,
        "value": 3
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 42,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 42,
        "col": 17,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 42,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 42,
        "col": 24,
        "value": "PUNTOS"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 42,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "20",
        "line": 42,
        "col": 31,
        "value": 20
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 42,
        "col": 33,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 42,
        "col": 34,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "660",
        "line": 42,
        "col": 40,
        "value": 660
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 42,
        "col": 43,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "430",
        "line": 43,
        "col": 1,
        "value": 430
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 43,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 43,
        "col": 8,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 43,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 43,
        "col": 10,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 43,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 43,
        "col": 17,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 43,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 43,
        "col": 24,
        "value": "PUNTOS"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 43,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 43,
        "col": 31,
        "value": 5
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 43,
        "col": 32,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 43,
        "col": 33,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "660",
        "line": 43,
        "col": 39,
        "value": 660
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 43,
        "col": 42,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "440",
        "line": 44,
        "col": 1,
        "value": 440
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 44,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 44,
        "col": 8,
        "value": "Y1"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 44,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 44,
        "col": 11,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 44,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ya",
        "line": 44,
        "col": 18,
        "value": "YA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 44,
        "col": 20,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 44,
        "col": 21,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 44,
        "col": 22,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "450",
        "line": 45,
        "col": 1,
        "value": 450
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 45,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 45,
        "col": 12,
        "value": "X"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 45,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 45,
        "col": 14,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 45,
        "col": 15,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 45,
        "col": 16,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 45,
        "col": 21,
        "value": " "
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 45,
        "col": 24,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 45,
        "col": 25,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 45,
        "col": 32,
        "value": "X1"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 45,
        "col": 34,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 45,
        "col": 35,
        "value": "Y1"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 45,
        "col": 37,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 45,
        "col": 38,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 45,
        "col": 44,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 45,
        "col": 48,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "231",
        "line": 45,
        "col": 49,
        "value": 231
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 45,
        "col": 52,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 45,
        "col": 53,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 45,
        "col": 54,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 45,
        "col": 55,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x1",
        "line": 45,
        "col": 56,
        "value": "X1"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 45,
        "col": 58,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 45,
        "col": 59,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 45,
        "col": 60,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y1",
        "line": 45,
        "col": 61,
        "value": "Y1"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 45,
        "col": 63,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "460",
        "line": 46,
        "col": 1,
        "value": 460
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 46,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 46,
        "col": 8,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 46,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 46,
        "col": 10,
        "value": 1
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 46,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 46,
        "col": 15,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 46,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 46,
        "col": 17,
        "value": 3
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 46,
        "col": 19,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 46,
        "col": 22,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 46,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "38",
        "line": 46,
        "col": 24,
        "value": 38
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 46,
        "col": 27,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 46,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "129",
        "line": 46,
        "col": 38,
        "value": 129
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 46,
        "col": 41,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "78",
        "line": 46,
        "col": 42,
        "value": 78
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 46,
        "col": 44,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 46,
        "col": 45,
        "value": 8
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 46,
        "col": 46,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "7",
        "line": 46,
        "col": 47,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 46,
        "col": 48,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 46,
        "col": 49,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 46,
        "col": 50,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 46,
        "col": 51,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 46,
        "col": 52,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "470",
        "line": 47,
        "col": 1,
        "value": 470
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 47,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "340",
        "line": 47,
        "col": 10,
        "value": 340
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 47,
        "col": 13,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "480",
        "line": 48,
        "col": 1,
        "value": 480
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 48,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 48,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "490",
        "line": 49,
        "col": 1,
        "value": 490
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 49,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 49,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "500",
        "line": 50,
        "col": 1,
        "value": 500
    },
    {
        "type": "IDENT",
        "lexeme": "pelotas",
        "line": 50,
        "col": 5,
        "value": "PELOTAS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 50,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "pelotas",
        "line": 50,
        "col": 13,
        "value": "PELOTAS"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 50,
        "col": 20,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 50,
        "col": 21,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 50,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "132",
        "line": 50,
        "col": 29,
        "value": 132
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 50,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "19",
        "line": 50,
        "col": 33,
        "value": 19
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 50,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "46",
        "line": 50,
        "col": 36,
        "value": 46
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 50,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "12",
        "line": 50,
        "col": 39,
        "value": 12
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 50,
        "col": 41,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 50,
        "col": 42,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 50,
        "col": 43,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 50,
        "col": 44,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 45,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 50,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "pelotas",
        "line": 50,
        "col": 49,
        "value": "PELOTAS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 50,
        "col": 56,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 50,
        "col": 57,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 50,
        "col": 59,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 50,
        "col": 64,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "620",
        "line": 50,
        "col": 69,
        "value": 620
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 50,
        "col": 72,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "510",
        "line": 51,
        "col": 1,
        "value": 510
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 51,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "660",
        "line": 51,
        "col": 11,
        "value": 660
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 51,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 51,
        "col": 15,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "280",
        "line": 51,
        "col": 20,
        "value": 280
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 51,
        "col": 23,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "520",
        "line": 52,
        "col": 1,
        "value": 520
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 52,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 52,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "530",
        "line": 53,
        "col": 1,
        "value": 530
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 53,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 53,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "540",
        "line": 54,
        "col": 1,
        "value": 540
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 54,
        "col": 5,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 54,
        "col": 8,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY",
        "line": 54,
        "col": 9,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 54,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 54,
        "col": 15,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 54,
        "col": 16,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 54,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 54,
        "col": 18,
        "value": 0
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 54,
        "col": 20,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY",
        "line": 54,
        "col": 23,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 54,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "74",
        "line": 54,
        "col": 29,
        "value": 74
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 54,
        "col": 31,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 54,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 54,
        "col": 33,
        "value": 0
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 54,
        "col": 34,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 54,
        "col": 36,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 54,
        "col": 40,
        "value": "BX"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 54,
        "col": 42,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 54,
        "col": 43,
        "value": 2
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 54,
        "col": 45,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 54,
        "col": 50,
        "value": "BX"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 54,
        "col": 52,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 54,
        "col": 53,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 54,
        "col": 55,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 54,
        "col": 56,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 54,
        "col": 57,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 54,
        "col": 58,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 54,
        "col": 64,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "550",
        "line": 55,
        "col": 1,
        "value": 550
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 55,
        "col": 5,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 55,
        "col": 8,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY",
        "line": 55,
        "col": 9,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 55,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 55,
        "col": 15,
        "value": 1
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 55,
        "col": 16,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 55,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 55,
        "col": 18,
        "value": 0
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 55,
        "col": 20,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY",
        "line": 55,
        "col": 23,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 55,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "75",
        "line": 55,
        "col": 29,
        "value": 75
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 55,
        "col": 31,
        "value": null
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 55,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 55,
        "col": 33,
        "value": 0
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 55,
        "col": 34,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 55,
        "col": 36,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 55,
        "col": 40,
        "value": "BX"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 55,
        "col": 42,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 55,
        "col": 43,
        "value": 32
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 55,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 55,
        "col": 51,
        "value": "BX"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 55,
        "col": 53,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bx",
        "line": 55,
        "col": 54,
        "value": "BX"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 55,
        "col": 56,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 55,
        "col": 57,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 55,
        "col": 58,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 55,
        "col": 59,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 55,
        "col": 65,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "560",
        "line": 56,
        "col": 1,
        "value": 560
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 56,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 56,
        "col": 11,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "570",
        "line": 57,
        "col": 1,
        "value": 570
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 57,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 57,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "580",
        "line": 58,
        "col": 1,
        "value": 580
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 58,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 58,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "590",
        "line": 59,
        "col": 1,
        "value": 590
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 59,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "xz",
        "line": 59,
        "col": 12,
        "value": "XZ"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 59,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "yz",
        "line": 59,
        "col": 15,
        "value": "YZ"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 59,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 59,
        "col": 18,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 59,
        "col": 23,
        "value": " "
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 59,
        "col": 26,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 59,
        "col": 27,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 59,
        "col": 33,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "600",
        "line": 60,
        "col": 1,
        "value": 600
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 60,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 60,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "610",
        "line": 61,
        "col": 1,
        "value": 610
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 61,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 61,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "620",
        "line": 62,
        "col": 1,
        "value": 620
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 62,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 62,
        "col": 8,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": ">=",
        "line": 62,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maximo",
        "line": 62,
        "col": 16,
        "value": "MAXIMO"
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 62,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maximo",
        "line": 62,
        "col": 28,
        "value": "MAXIMO"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 62,
        "col": 34,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 62,
        "col": 35,
        "value": "PUNTOS"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 62,
        "col": 41,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "630",
        "line": 63,
        "col": 1,
        "value": 630
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 63,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "660",
        "line": 63,
        "col": 11,
        "value": 660
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 63,
        "col": 15,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 63,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 63,
        "col": 22,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "pelotas",
        "line": 63,
        "col": 24,
        "value": "PELOTAS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 63,
        "col": 31,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 63,
        "col": 32,
        "value": 5
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 33,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 63,
        "col": 34,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "130",
        "line": 63,
        "col": 39,
        "value": 130
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 63,
        "col": 42,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "640",
        "line": 64,
        "col": 1,
        "value": 640
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 64,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 64,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "650",
        "line": 65,
        "col": 1,
        "value": 650
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 65,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 65,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "660",
        "line": 66,
        "col": 1,
        "value": 660
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 66,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "130",
        "line": 66,
        "col": 11,
        "value": 130
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 66,
        "col": 15,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "20",
        "line": 66,
        "col": 17,
        "value": 20
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "13",
        "line": 66,
        "col": 20,
        "value": 13
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 22,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 66,
        "col": 23,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 24,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 66,
        "col": 25,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 26,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "31",
        "line": 66,
        "col": 27,
        "value": 31
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 66,
        "col": 29,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 66,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 66,
        "col": 37,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 66,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 66,
        "col": 39,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 66,
        "col": 41,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 66,
        "col": 42,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Maximo\"",
        "line": 66,
        "col": 47,
        "value": "Maximo"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 66,
        "col": 55,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maximo",
        "line": 66,
        "col": 56,
        "value": "MAXIMO"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 66,
        "col": 62,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "670",
        "line": 67,
        "col": 1,
        "value": 670
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 67,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 67,
        "col": 12,
        "value": 15
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 67,
        "col": 15,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 67,
        "col": 18,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Puntos\"",
        "line": 67,
        "col": 24,
        "value": "Puntos"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 67,
        "col": 32,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 67,
        "col": 33,
        "value": "PUNTOS"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 39,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 67,
        "col": 40,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "30",
        "line": 67,
        "col": 47,
        "value": 30
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 49,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 67,
        "col": 50,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 52,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 67,
        "col": 53,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Pelotas\"",
        "line": 67,
        "col": 58,
        "value": "Pelotas"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 67,
        "col": 67,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "pelotas",
        "line": 67,
        "col": 68,
        "value": "PELOTAS"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 75,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 67,
        "col": 76,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 67,
        "col": 82,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "680",
        "line": 68,
        "col": 1,
        "value": 680
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 68,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 68,
        "col": 12,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 68,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "23",
        "line": 68,
        "col": 14,
        "value": 23
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 68,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 68,
        "col": 17,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Pulse barra espaciadora para empezar\"",
        "line": 68,
        "col": 22,
        "value": "Pulse barra espaciadora para empezar"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 68,
        "col": 60,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 68,
        "col": 61,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 68,
        "col": 67,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "690",
        "line": 69,
        "col": 1,
        "value": 690
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 69,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 69,
        "col": 12,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 69,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 69,
        "col": 14,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 69,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 69,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SPACE$",
        "line": 69,
        "col": 23,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 69,
        "col": 29,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "40",
        "line": 69,
        "col": 30,
        "value": 40
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 69,
        "col": 32,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 69,
        "col": 33,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 69,
        "col": 34,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 69,
        "col": 35,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 69,
        "col": 41,
        "value": null
    },
    {
        "type": "EOF",
        "lexeme": "",
        "line": 70,
        "col": 1,
        "value": null
    }
]