[
    {
        "type": "LINE_NUMBER",
        "lexeme": "10",
        "line": 1,
        "col": 1,
        "value": 10
    },
    {
        "type": "COMMENT",
        "lexeme": "BOMBARDERO por DAVE TOWN",
        "line": 1,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 1,
        "col": 29,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "20",
        "line": 2,
        "col": 1,
        "value": 20
    },
    {
        "type": "COMMENT",
        "lexeme": "copyright (c) AMSOFT 1984",
        "line": 2,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 2,
        "col": 30,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "30",
        "line": 3,
        "col": 1,
        "value": 30
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 3,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 3,
        "col": 5,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "40",
        "line": 4,
        "col": 1,
        "value": 40
    },
    {
        "type": "KEYWORD",
        "lexeme": "MODE",
        "line": 4,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 4,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CLS",
        "line": 4,
        "col": 11,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 15,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 4,
        "col": 19,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 20,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 4,
        "col": 21,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "BORDER",
        "line": 4,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 4,
        "col": 30,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 31,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 4,
        "col": 36,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 37,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "18",
        "line": 4,
        "col": 38,
        "value": 18
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 40,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 41,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 4,
        "col": 45,
        "value": 2
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 46,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "6",
        "line": 4,
        "col": 47,
        "value": 6
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 48,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 49,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 4,
        "col": 53,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 54,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 4,
        "col": 55,
        "value": 4
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 56,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 57,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 4,
        "col": 61,
        "value": 5
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 62,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 4,
        "col": 63,
        "value": 15
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 65,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 66,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "6",
        "line": 4,
        "col": 70,
        "value": 6
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 71,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 4,
        "col": 72,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 73,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 74,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "7",
        "line": 4,
        "col": 78,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 79,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 4,
        "col": 80,
        "value": 24
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 82,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 83,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 4,
        "col": 87,
        "value": 8
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 88,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 4,
        "col": 89,
        "value": 8
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 90,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 91,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "9",
        "line": 4,
        "col": 95,
        "value": 9
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 96,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "26",
        "line": 4,
        "col": 97,
        "value": 26
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 99,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 100,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 4,
        "col": 104,
        "value": 10
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 106,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 4,
        "col": 107,
        "value": 10
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 109,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 110,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "11",
        "line": 4,
        "col": 114,
        "value": 11
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 116,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "20",
        "line": 4,
        "col": 117,
        "value": 20
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 119,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 120,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "12",
        "line": 4,
        "col": 124,
        "value": 12
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 126,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "12",
        "line": 4,
        "col": 127,
        "value": 12
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 129,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 130,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "13",
        "line": 4,
        "col": 134,
        "value": 13
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 136,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 4,
        "col": 137,
        "value": 16
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 139,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 140,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "14",
        "line": 4,
        "col": 144,
        "value": 14
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 146,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "14",
        "line": 4,
        "col": 147,
        "value": 14
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 4,
        "col": 149,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INK",
        "line": 4,
        "col": 150,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 4,
        "col": 154,
        "value": 15
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 4,
        "col": 156,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "21",
        "line": 4,
        "col": 157,
        "value": 21
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 4,
        "col": 159,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "50",
        "line": 5,
        "col": 1,
        "value": 50
    },
    {
        "type": "KEYWORD",
        "lexeme": "SYMBOL AFTER",
        "line": 5,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "240",
        "line": 5,
        "col": 17,
        "value": 240
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 5,
        "col": 20,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SYMBOL",
        "line": 5,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "241",
        "line": 5,
        "col": 28,
        "value": 241
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 31,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H40",
        "line": 5,
        "col": 32,
        "value": 64
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H60",
        "line": 5,
        "col": 36,
        "value": 96
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 39,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H70",
        "line": 5,
        "col": 40,
        "value": 112
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 43,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H7F",
        "line": 5,
        "col": 44,
        "value": 127
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 47,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H7F",
        "line": 5,
        "col": 48,
        "value": 127
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 51,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&HEF",
        "line": 5,
        "col": 52,
        "value": 239
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 55,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H7",
        "line": 5,
        "col": 56,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 58,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H0",
        "line": 5,
        "col": 59,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 5,
        "col": 61,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SYMBOL",
        "line": 5,
        "col": 62,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "242",
        "line": 5,
        "col": 69,
        "value": 242
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 72,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H0",
        "line": 5,
        "col": 73,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 75,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H32",
        "line": 5,
        "col": 76,
        "value": 50
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 79,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H7A",
        "line": 5,
        "col": 80,
        "value": 122
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 83,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&HFE",
        "line": 5,
        "col": 84,
        "value": 254
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 87,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&HFA",
        "line": 5,
        "col": 88,
        "value": 250
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 91,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&HF2",
        "line": 5,
        "col": 92,
        "value": 242
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 95,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&HE0",
        "line": 5,
        "col": 96,
        "value": 224
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 5,
        "col": 99,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "&H0",
        "line": 5,
        "col": 100,
        "value": 0
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 5,
        "col": 102,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "60",
        "line": 6,
        "col": 1,
        "value": 60
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 6,
        "col": 4,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 6,
        "col": 11,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maxi",
        "line": 6,
        "col": 13,
        "value": "MAXI"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 6,
        "col": 18,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 19,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "avi$",
        "line": 6,
        "col": 20,
        "value": "AVI$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 24,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 6,
        "col": 25,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 6,
        "col": 29,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "241",
        "line": 6,
        "col": 30,
        "value": 241
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 6,
        "col": 33,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 6,
        "col": 34,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 6,
        "col": 35,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 6,
        "col": 39,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "242",
        "line": 6,
        "col": 40,
        "value": 242
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 6,
        "col": 43,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 44,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 6,
        "col": 45,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 46,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 6,
        "col": 47,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 48,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 6,
        "col": 49,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 50,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 6,
        "col": 51,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 52,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 6,
        "col": 53,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 56,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 6,
        "col": 57,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 58,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 6,
        "col": 59,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 60,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 6,
        "col": 61,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 6,
        "col": 62,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 6,
        "col": 63,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 6,
        "col": 64,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 6,
        "col": 65,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 6,
        "col": 66,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "70",
        "line": 7,
        "col": 1,
        "value": 70
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOSUB",
        "line": 7,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "480",
        "line": 7,
        "col": 10,
        "value": 480
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 7,
        "col": 13,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "80",
        "line": 8,
        "col": 1,
        "value": 80
    },
    {
        "type": "KEYWORD",
        "lexeme": "CLS",
        "line": 8,
        "col": 4,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 8,
        "col": 7,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "90",
        "line": 9,
        "col": 1,
        "value": 90
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 9,
        "col": 4,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 9,
        "col": 8,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 9,
        "col": 9,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 9,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 9,
        "col": 17,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 18,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 9,
        "col": 19,
        "value": 15
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 9,
        "col": 21,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INPUT",
        "line": 9,
        "col": 22,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Elija nivel: 0 (AS) a 5 (PRINCIPIANTE) \"",
        "line": 9,
        "col": 27,
        "value": "Elija nivel: 0 (AS) a 5 (PRINCIPIANTE) "
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 9,
        "col": 68,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 9,
        "col": 69,
        "value": "NIVEL"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 9,
        "col": 74,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "100",
        "line": 10,
        "col": 1,
        "value": 100
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 10,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 10,
        "col": 8,
        "value": "NIVEL"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 10,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 10,
        "col": 14,
        "value": 0
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 10,
        "col": 16,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 10,
        "col": 19,
        "value": "NIVEL"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 10,
        "col": 24,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 10,
        "col": 25,
        "value": 5
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 10,
        "col": 27,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 10,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "90",
        "line": 10,
        "col": 37,
        "value": 90
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 10,
        "col": 39,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "110",
        "line": 11,
        "col": 1,
        "value": 110
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 11,
        "col": 5,
        "value": "NIVEL"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 11,
        "col": 10,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 11,
        "col": 11,
        "value": "NIVEL"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 11,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 11,
        "col": 17,
        "value": 10
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 11,
        "col": 19,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "120",
        "line": 12,
        "col": 1,
        "value": 120
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 12,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 12,
        "col": 12,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 12,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 12,
        "col": 14,
        "value": 15
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 12,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 12,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 12,
        "col": 23,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 12,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "18",
        "line": 12,
        "col": 28,
        "value": 18
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 12,
        "col": 30,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 12,
        "col": 31,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 12,
        "col": 32,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 12,
        "col": 33,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 12,
        "col": 40,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 12,
        "col": 41,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 12,
        "col": 42,
        "value": 15
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 12,
        "col": 44,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INPUT",
        "line": 12,
        "col": 45,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Elija velocidad: 0 (MAX) a 100(MIN) \"",
        "line": 12,
        "col": 50,
        "value": "Elija velocidad: 0 (MAX) a 100(MIN) "
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 12,
        "col": 88,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 12,
        "col": 89,
        "value": "VEL"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 12,
        "col": 92,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "130",
        "line": 13,
        "col": 1,
        "value": 130
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 13,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 13,
        "col": 8,
        "value": "VEL"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 13,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "100",
        "line": 13,
        "col": 12,
        "value": 100
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 13,
        "col": 16,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 13,
        "col": 19,
        "value": "VEL"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 13,
        "col": 22,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 13,
        "col": 23,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 13,
        "col": 25,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "120",
        "line": 13,
        "col": 30,
        "value": 120
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 13,
        "col": 33,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "140",
        "line": 14,
        "col": 1,
        "value": 140
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 14,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 14,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "150",
        "line": 15,
        "col": 1,
        "value": 150
    },
    {
        "type": "COMMENT",
        "lexeme": "Edificios",
        "line": 15,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 15,
        "col": 15,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "160",
        "line": 16,
        "col": 1,
        "value": 160
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 16,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 16,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "170",
        "line": 17,
        "col": 1,
        "value": 170
    },
    {
        "type": "KEYWORD",
        "lexeme": "MODE",
        "line": 17,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 17,
        "col": 10,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 11,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 17,
        "col": 12,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "base",
        "line": 17,
        "col": 16,
        "value": "BASE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 17,
        "col": 20,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 17,
        "col": 21,
        "value": 5
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 17,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 17,
        "col": 26,
        "value": 15
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 28,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 17,
        "col": 29,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "altura",
        "line": 17,
        "col": 33,
        "value": "ALTURA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 17,
        "col": 39,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "21",
        "line": 17,
        "col": 40,
        "value": 21
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 17,
        "col": 43,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INT",
        "line": 17,
        "col": 46,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 17,
        "col": 49,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RND",
        "line": 17,
        "col": 50,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 17,
        "col": 53,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 17,
        "col": 54,
        "value": 1
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 17,
        "col": 55,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 17,
        "col": 56,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 17,
        "col": 57,
        "value": 8
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 17,
        "col": 58,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 17,
        "col": 59,
        "value": "NIVEL"
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 17,
        "col": 64,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "STEP",
        "line": 17,
        "col": 66,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 17,
        "col": 70,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 17,
        "col": 71,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 72,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 17,
        "col": 73,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "base",
        "line": 17,
        "col": 80,
        "value": "BASE"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 17,
        "col": 84,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "altura",
        "line": 17,
        "col": 85,
        "value": "ALTURA"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 91,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 17,
        "col": 92,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "base",
        "line": 17,
        "col": 96,
        "value": "BASE"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 17,
        "col": 100,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 17,
        "col": 101,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 102,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 17,
        "col": 103,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 17,
        "col": 109,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 17,
        "col": 113,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "143",
        "line": 17,
        "col": 114,
        "value": 143
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 17,
        "col": 117,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 17,
        "col": 118,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 17,
        "col": 119,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 17,
        "col": 123,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 17,
        "col": 124,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 17,
        "col": 125,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 17,
        "col": 126,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 17,
        "col": 127,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 17,
        "col": 131,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "11",
        "line": 17,
        "col": 132,
        "value": 11
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 17,
        "col": 134,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 17,
        "col": 135,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 17,
        "col": 136,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 17,
        "col": 140,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "244",
        "line": 17,
        "col": 141,
        "value": 244
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 17,
        "col": 144,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 17,
        "col": 145,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 146,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 17,
        "col": 147,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 17,
        "col": 151,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 17,
        "col": 152,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 17,
        "col": 156,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "180",
        "line": 18,
        "col": 1,
        "value": 180
    },
    {
        "type": "KEYWORD",
        "lexeme": "PLOT",
        "line": 18,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 18,
        "col": 10,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 18,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "20",
        "line": 18,
        "col": 12,
        "value": 20
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 18,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 18,
        "col": 15,
        "value": 4
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 18,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "DRAW",
        "line": 18,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "640",
        "line": 18,
        "col": 22,
        "value": 640
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 18,
        "col": 25,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "20",
        "line": 18,
        "col": 26,
        "value": 20
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 18,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 18,
        "col": 29,
        "value": 4
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 18,
        "col": 30,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "190",
        "line": 19,
        "col": 1,
        "value": 190
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 19,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 19,
        "col": 12,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 19,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 19,
        "col": 14,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 19,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 19,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 19,
        "col": 21,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 19,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 19,
        "col": 23,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"PUNTOS\"",
        "line": 19,
        "col": 28,
        "value": "PUNTOS"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 19,
        "col": 36,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 19,
        "col": 37,
        "value": "PUNTOS"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 19,
        "col": 43,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 19,
        "col": 44,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 19,
        "col": 45,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "13",
        "line": 19,
        "col": 52,
        "value": 13
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 19,
        "col": 54,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 19,
        "col": 55,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 19,
        "col": 57,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 19,
        "col": 58,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"MAX\"",
        "line": 19,
        "col": 63,
        "value": "MAX"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 19,
        "col": 68,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maxi",
        "line": 19,
        "col": 69,
        "value": "MAXI"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 19,
        "col": 73,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 19,
        "col": 74,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "200",
        "line": 20,
        "col": 1,
        "value": 200
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 20,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 20,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "210",
        "line": 21,
        "col": 1,
        "value": 210
    },
    {
        "type": "COMMENT",
        "lexeme": "Juego",
        "line": 21,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 21,
        "col": 11,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "220",
        "line": 22,
        "col": 1,
        "value": 220
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 22,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 22,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "230",
        "line": 23,
        "col": 1,
        "value": 230
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 23,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 23,
        "col": 12,
        "value": "X"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 23,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 23,
        "col": 14,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 23,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 23,
        "col": 16,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 23,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 23,
        "col": 18,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 23,
        "col": 23,
        "value": " "
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 23,
        "col": 26,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 23,
        "col": 27,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "240",
        "line": 24,
        "col": 1,
        "value": 240
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 24,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 24,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 24,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 24,
        "col": 11,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 24,
        "col": 18,
        "value": "X"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 24,
        "col": 19,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 24,
        "col": 20,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 24,
        "col": 21,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 24,
        "col": 22,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "avi$",
        "line": 24,
        "col": 28,
        "value": "AVI$"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 24,
        "col": 32,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 24,
        "col": 33,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 24,
        "col": 34,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 24,
        "col": 38,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 24,
        "col": 39,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "250",
        "line": 25,
        "col": 1,
        "value": 250
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 25,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 25,
        "col": 8,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 25,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "21",
        "line": 25,
        "col": 10,
        "value": 21
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 25,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 25,
        "col": 17,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 25,
        "col": 18,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 25,
        "col": 19,
        "value": 15
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 25,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 25,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "290",
        "line": 25,
        "col": 32,
        "value": 290
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 25,
        "col": 35,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "ELSE",
        "line": 25,
        "col": 36,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 25,
        "col": 41,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "340",
        "line": 25,
        "col": 46,
        "value": 340
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 25,
        "col": 49,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "260",
        "line": 26,
        "col": 1,
        "value": 260
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 26,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 26,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "270",
        "line": 27,
        "col": 1,
        "value": 270
    },
    {
        "type": "COMMENT",
        "lexeme": "Aterriza",
        "line": 27,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 27,
        "col": 14,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "280",
        "line": 28,
        "col": 1,
        "value": 280
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 28,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 28,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "290",
        "line": 29,
        "col": 1,
        "value": 290
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 29,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "c",
        "line": 29,
        "col": 9,
        "value": "C"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 29,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 29,
        "col": 11,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 29,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1000",
        "line": 29,
        "col": 16,
        "value": 1000
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 29,
        "col": 20,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 29,
        "col": 21,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 29,
        "col": 25,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "300",
        "line": 30,
        "col": 1,
        "value": 300
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 30,
        "col": 5,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 11,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 30,
        "col": 12,
        "value": "PUNTOS"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 30,
        "col": 18,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "100",
        "line": 30,
        "col": 19,
        "value": 100
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 30,
        "col": 22,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 30,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 30,
        "col": 24,
        "value": "NIVEL"
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 30,
        "col": 29,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 30,
        "col": 30,
        "value": 2
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 30,
        "col": 31,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 30,
        "col": 32,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 30,
        "col": 33,
        "value": "NIVEL"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 38,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 30,
        "col": 39,
        "value": "NIVEL"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 30,
        "col": 44,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 30,
        "col": 45,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 30,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 30,
        "col": 47,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 48,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 30,
        "col": 49,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 30,
        "col": 50,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 30,
        "col": 51,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 52,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 30,
        "col": 53,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 30,
        "col": 54,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 30,
        "col": 55,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 56,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 30,
        "col": 57,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 30,
        "col": 58,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 30,
        "col": 59,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 60,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 30,
        "col": 61,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 30,
        "col": 62,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 30,
        "col": 63,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 30,
        "col": 66,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 30,
        "col": 67,
        "value": 0
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 30,
        "col": 68,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "310",
        "line": 31,
        "col": 1,
        "value": 310
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 31,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 31,
        "col": 8,
        "value": "NIVEL"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 31,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 31,
        "col": 14,
        "value": 10
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 31,
        "col": 17,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "nivel",
        "line": 31,
        "col": 22,
        "value": "NIVEL"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 31,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 31,
        "col": 28,
        "value": 10
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 31,
        "col": 30,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 31,
        "col": 31,
        "value": "VEL"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 31,
        "col": 34,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 31,
        "col": 35,
        "value": "VEL"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 31,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "20",
        "line": 31,
        "col": 39,
        "value": 20
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 31,
        "col": 41,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "320",
        "line": 32,
        "col": 1,
        "value": 320
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 32,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 32,
        "col": 8,
        "value": "VEL"
    },
    {
        "type": "COMP",
        "lexeme": "<",
        "line": 32,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 32,
        "col": 12,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 32,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 32,
        "col": 19,
        "value": "VEL"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 32,
        "col": 22,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 32,
        "col": 23,
        "value": 0
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 32,
        "col": 24,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "330",
        "line": 33,
        "col": 1,
        "value": 330
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 33,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "150",
        "line": 33,
        "col": 10,
        "value": 150
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 33,
        "col": 13,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "340",
        "line": 34,
        "col": 1,
        "value": 340
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 34,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "c",
        "line": 34,
        "col": 9,
        "value": "C"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 34,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 34,
        "col": 11,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 34,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "vel",
        "line": 34,
        "col": 16,
        "value": "VEL"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 34,
        "col": 19,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 34,
        "col": 20,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 34,
        "col": 24,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "350",
        "line": 35,
        "col": 1,
        "value": 350
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 35,
        "col": 5,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 35,
        "col": 6,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 35,
        "col": 7,
        "value": "X"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 35,
        "col": 8,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 35,
        "col": 9,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 35,
        "col": 10,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "360",
        "line": 36,
        "col": 1,
        "value": 360
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 36,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 36,
        "col": 8,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 36,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "18",
        "line": 36,
        "col": 10,
        "value": 18
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 36,
        "col": 13,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 36,
        "col": 18,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 36,
        "col": 25,
        "value": "X"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 36,
        "col": 26,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 36,
        "col": 27,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 36,
        "col": 28,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 36,
        "col": 29,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 30,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 36,
        "col": 31,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 36,
        "col": 37,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 36,
        "col": 41,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "18",
        "line": 36,
        "col": 42,
        "value": 18
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 36,
        "col": 44,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 36,
        "col": 45,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 36,
        "col": 47,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 36,
        "col": 48,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 36,
        "col": 49,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 50,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 36,
        "col": 51,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 36,
        "col": 52,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 36,
        "col": 53,
        "value": "Y"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 36,
        "col": 54,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 36,
        "col": 55,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 56,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 36,
        "col": 57,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 36,
        "col": 64,
        "value": "X"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 36,
        "col": 65,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 36,
        "col": 66,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 67,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 36,
        "col": 68,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 36,
        "col": 72,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 73,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 36,
        "col": 74,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "avi$",
        "line": 36,
        "col": 80,
        "value": "AVI$"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 36,
        "col": 84,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 36,
        "col": 85,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 36,
        "col": 86,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 36,
        "col": 90,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 36,
        "col": 91,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "370",
        "line": 37,
        "col": 1,
        "value": 370
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 37,
        "col": 5,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 7,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY$",
        "line": 37,
        "col": 8,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 37,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 37,
        "col": 18,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 20,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 37,
        "col": 21,
        "value": " "
    },
    {
        "type": "OP",
        "lexeme": "AND",
        "line": 37,
        "col": 25,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 37,
        "col": 29,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 32,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 37,
        "col": 33,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 37,
        "col": 35,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 37,
        "col": 40,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 43,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 37,
        "col": 44,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 45,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 37,
        "col": 46,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 47,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 37,
        "col": 48,
        "value": "Y"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 37,
        "col": 49,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 37,
        "col": 50,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 37,
        "col": 51,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 37,
        "col": 52,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 37,
        "col": 53,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 37,
        "col": 54,
        "value": "X"
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 37,
        "col": 55,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "380",
        "line": 38,
        "col": 1,
        "value": 380
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 38,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 38,
        "col": 8,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 38,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "21",
        "line": 38,
        "col": 10,
        "value": 21
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 38,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 38,
        "col": 18,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 38,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 38,
        "col": 22,
        "value": 0
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 38,
        "col": 23,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "390",
        "line": 39,
        "col": 1,
        "value": 390
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 39,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 39,
        "col": 8,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 39,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 39,
        "col": 12,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 39,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 39,
        "col": 19,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 39,
        "col": 26,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 27,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 28,
        "value": "B"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 29,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 39,
        "col": 30,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 39,
        "col": 36,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 39,
        "col": 40,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "252",
        "line": 39,
        "col": 41,
        "value": 252
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 39,
        "col": 44,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 39,
        "col": 45,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 46,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 39,
        "col": 47,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 39,
        "col": 54,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 55,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 56,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 39,
        "col": 57,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 39,
        "col": 58,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 59,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 39,
        "col": 60,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 39,
        "col": 65,
        "value": " "
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 39,
        "col": 68,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 69,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 70,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 39,
        "col": 71,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 72,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 39,
        "col": 73,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 39,
        "col": 74,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 75,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 39,
        "col": 76,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 79,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 39,
        "col": 80,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "21",
        "line": 39,
        "col": 81,
        "value": 21
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 39,
        "col": 84,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 39,
        "col": 89,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 39,
        "col": 96,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 97,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 98,
        "value": "B"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 99,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 39,
        "col": 100,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 39,
        "col": 105,
        "value": " "
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 39,
        "col": 108,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 109,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 39,
        "col": 110,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 39,
        "col": 117,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 118,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 119,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 39,
        "col": 120,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 39,
        "col": 121,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 122,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 39,
        "col": 123,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 39,
        "col": 128,
        "value": " "
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 39,
        "col": 131,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 132,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 39,
        "col": 133,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 39,
        "col": 140,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 141,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 142,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 39,
        "col": 143,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 39,
        "col": 144,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 145,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 39,
        "col": 146,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 39,
        "col": 151,
        "value": " "
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 154,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 39,
        "col": 155,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 39,
        "col": 156,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 39,
        "col": 157,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 158,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 39,
        "col": 159,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 39,
        "col": 160,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 39,
        "col": 161,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 162,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 39,
        "col": 163,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 39,
        "col": 166,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 39,
        "col": 167,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 39,
        "col": 168,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 39,
        "col": 169,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 39,
        "col": 175,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 176,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4000",
        "line": 39,
        "col": 177,
        "value": 4000
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 181,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 39,
        "col": 182,
        "value": 10
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 184,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "12",
        "line": 39,
        "col": 185,
        "value": 12
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 187,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 39,
        "col": 188,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 189,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 39,
        "col": 190,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 39,
        "col": 191,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 39,
        "col": 192,
        "value": 10
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 39,
        "col": 194,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "400",
        "line": 40,
        "col": 1,
        "value": 400
    },
    {
        "type": "IDENT",
        "lexeme": "ga",
        "line": 40,
        "col": 5,
        "value": "GA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 40,
        "col": 7,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 40,
        "col": 8,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 40,
        "col": 9,
        "value": "A"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 40,
        "col": 10,
        "value": null
    },
    {
        "type": "REAL",
        "lexeme": "0.5",
        "line": 40,
        "col": 11,
        "value": 0.5
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 40,
        "col": 14,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 40,
        "col": 15,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 40,
        "col": 16,
        "value": 32
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 40,
        "col": 18,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "gb",
        "line": 40,
        "col": 19,
        "value": "GB"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 40,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "400",
        "line": 40,
        "col": 22,
        "value": 400
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 40,
        "col": 25,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 40,
        "col": 26,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 40,
        "col": 27,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 40,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 40,
        "col": 29,
        "value": 16
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 40,
        "col": 31,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 40,
        "col": 32,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bomba",
        "line": 40,
        "col": 33,
        "value": "BOMBA"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 40,
        "col": 38,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "TEST",
        "line": 40,
        "col": 39,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 40,
        "col": 43,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "ga",
        "line": 40,
        "col": 44,
        "value": "GA"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 40,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "gb",
        "line": 40,
        "col": 47,
        "value": "GB"
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 40,
        "col": 49,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 40,
        "col": 50,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "410",
        "line": 41,
        "col": 1,
        "value": 410
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 41,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "bomba",
        "line": 41,
        "col": 8,
        "value": "BOMBA"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 41,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 41,
        "col": 14,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 41,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 41,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "670",
        "line": 41,
        "col": 26,
        "value": 670
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 41,
        "col": 29,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "420",
        "line": 42,
        "col": 1,
        "value": 420
    },
    {
        "type": "IDENT",
        "lexeme": "gx",
        "line": 42,
        "col": 5,
        "value": "GX"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 42,
        "col": 7,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 42,
        "col": 8,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 42,
        "col": 9,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 42,
        "col": 10,
        "value": "X"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 42,
        "col": 11,
        "value": null
    },
    {
        "type": "REAL",
        "lexeme": "1.5",
        "line": 42,
        "col": 12,
        "value": 1.5
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 42,
        "col": 15,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 42,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 42,
        "col": 17,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 42,
        "col": 19,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 42,
        "col": 20,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "gy",
        "line": 42,
        "col": 21,
        "value": "GY"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 42,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "408",
        "line": 42,
        "col": 24,
        "value": 408
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 42,
        "col": 27,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 42,
        "col": 28,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 42,
        "col": 29,
        "value": "Y"
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 42,
        "col": 30,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "16",
        "line": 42,
        "col": 31,
        "value": 16
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 42,
        "col": 33,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 42,
        "col": 34,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "choque",
        "line": 42,
        "col": 35,
        "value": "CHOQUE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 42,
        "col": 41,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "TEST",
        "line": 42,
        "col": 42,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 42,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "gx",
        "line": 42,
        "col": 47,
        "value": "GX"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 42,
        "col": 49,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "gy",
        "line": 42,
        "col": 50,
        "value": "GY"
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 42,
        "col": 52,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 42,
        "col": 53,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "430",
        "line": 43,
        "col": 1,
        "value": 430
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 43,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "choque",
        "line": 43,
        "col": 8,
        "value": "CHOQUE"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 43,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 43,
        "col": 15,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 43,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 43,
        "col": 22,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "570",
        "line": 43,
        "col": 27,
        "value": 570
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 43,
        "col": 30,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "440",
        "line": 44,
        "col": 1,
        "value": 440
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 44,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "230",
        "line": 44,
        "col": 10,
        "value": 230
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 44,
        "col": 13,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "450",
        "line": 45,
        "col": 1,
        "value": 450
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 45,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 45,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "460",
        "line": 46,
        "col": 1,
        "value": 460
    },
    {
        "type": "COMMENT",
        "lexeme": "Instrucciones",
        "line": 46,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 46,
        "col": 19,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "470",
        "line": 47,
        "col": 1,
        "value": 470
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 47,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 47,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "480",
        "line": 48,
        "col": 1,
        "value": 480
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 48,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 48,
        "col": 12,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 48,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 48,
        "col": 14,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 48,
        "col": 15,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 48,
        "col": 16,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 48,
        "col": 20,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 48,
        "col": 21,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 48,
        "col": 22,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Usted esta pilotando un avion sobre una ciudad desierta y tiene que pasar sobre los edificios para aterrizar y repostar.Su avion se mueve de izquierda a derecha.\"",
        "line": 48,
        "col": 27,
        "value": "Usted esta pilotando un avion sobre una ciudad desierta y tiene que pasar sobre los edificios para aterrizar y repostar.Su avion se mueve de izquierda a derecha."
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 48,
        "col": 190,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 48,
        "col": 191,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 48,
        "col": 192,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 48,
        "col": 197,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "490",
        "line": 49,
        "col": 1,
        "value": 490
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 49,
        "col": 5,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 49,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 49,
        "col": 11,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Al llegar a la derecha, el avion vuelve a salir por la izquierda, pero MAS BAJO.Dispone de un numero limitado de bombas y puede hacerlas caer sobre los edifici-cios pulsando la BARRA ESPACIADORA.\"",
        "line": 49,
        "col": 16,
        "value": "Al llegar a la derecha, el avion vuelve a salir por la izquierda, pero MAS BAJO.Dispone de un numero limitado de bombas y puede hacerlas caer sobre los edifici-cios pulsando la BARRA ESPACIADORA."
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 49,
        "col": 213,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 49,
        "col": 214,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 49,
        "col": 215,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 49,
        "col": 220,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "500",
        "line": 50,
        "col": 1,
        "value": 500
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 50,
        "col": 5,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 50,
        "col": 11,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Cada vez que aterriza, sube la alturade los edificios y la velocidad.\"",
        "line": 50,
        "col": 16,
        "value": "Cada vez que aterriza, sube la alturade los edificios y la velocidad."
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 50,
        "col": 87,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 88,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 50,
        "col": 89,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 94,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 50,
        "col": 95,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 100,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 50,
        "col": 101,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"UNA VEZ DISPARADA UNA BOMBA,YA NO PUEDE DISPARAR OTRAMIENTRAS NO HAYA EXPLOSIO-NADO LA PRIMERA!!!\"",
        "line": 50,
        "col": 106,
        "value": "UNA VEZ DISPARADA UNA BOMBA,YA NO PUEDE DISPARAR OTRAMIENTRAS NO HAYA EXPLOSIO-NADO LA PRIMERA!!!"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 50,
        "col": 205,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 50,
        "col": 206,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "510",
        "line": 51,
        "col": 1,
        "value": 510
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 51,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 51,
        "col": 9,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 51,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 51,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 51,
        "col": 18,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 51,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 51,
        "col": 20,
        "value": 24
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 51,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 51,
        "col": 23,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 51,
        "col": 28,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 51,
        "col": 29,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Pulse una tecla para empezar.\"",
        "line": 51,
        "col": 34,
        "value": "Pulse una tecla para empezar."
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 51,
        "col": 65,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 51,
        "col": 66,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "520",
        "line": 52,
        "col": 1,
        "value": 520
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 52,
        "col": 5,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 52,
        "col": 7,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY$",
        "line": 52,
        "col": 8,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 52,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 52,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 52,
        "col": 18,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 52,
        "col": 20,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"\"",
        "line": 52,
        "col": 21,
        "value": ""
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 52,
        "col": 24,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "520",
        "line": 52,
        "col": 29,
        "value": 520
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 52,
        "col": 32,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "530",
        "line": 53,
        "col": 1,
        "value": 530
    },
    {
        "type": "KEYWORD",
        "lexeme": "RETURN",
        "line": 53,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 53,
        "col": 11,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "540",
        "line": 54,
        "col": 1,
        "value": 540
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 54,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 54,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "550",
        "line": 55,
        "col": 1,
        "value": 550
    },
    {
        "type": "COMMENT",
        "lexeme": "Colision",
        "line": 55,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 55,
        "col": 14,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "560",
        "line": 56,
        "col": 1,
        "value": 560
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 56,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 56,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "570",
        "line": 57,
        "col": 1,
        "value": 570
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 57,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 57,
        "col": 12,
        "value": "X"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 57,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 57,
        "col": 14,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 57,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 57,
        "col": 16,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 57,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 57,
        "col": 18,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 24,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 28,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 57,
        "col": 29,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 31,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 57,
        "col": 32,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 33,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 37,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 57,
        "col": 38,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 40,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 57,
        "col": 41,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 42,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 46,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 57,
        "col": 47,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 49,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 57,
        "col": 50,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 51,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 55,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "253",
        "line": 57,
        "col": 56,
        "value": 253
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 59,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 57,
        "col": 60,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 61,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 65,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 57,
        "col": 66,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 67,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 57,
        "col": 68,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 69,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 73,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "238",
        "line": 57,
        "col": 74,
        "value": 238
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 77,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 57,
        "col": 78,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 57,
        "col": 79,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 57,
        "col": 83,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 57,
        "col": 84,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 57,
        "col": 85,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 57,
        "col": 86,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 57,
        "col": 87,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "580",
        "line": 58,
        "col": 1,
        "value": 580
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 58,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 58,
        "col": 9,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 58,
        "col": 10,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 58,
        "col": 11,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 58,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 58,
        "col": 16,
        "value": 10
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 18,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 58,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "7",
        "line": 58,
        "col": 25,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 58,
        "col": 26,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4000",
        "line": 58,
        "col": 27,
        "value": 4000
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 58,
        "col": 31,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 58,
        "col": 32,
        "value": 5
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 58,
        "col": 33,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "15",
        "line": 58,
        "col": 34,
        "value": 15
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 58,
        "col": 36,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 58,
        "col": 37,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 58,
        "col": 38,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 58,
        "col": 39,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 58,
        "col": 40,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 58,
        "col": 41,
        "value": 5
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 42,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 58,
        "col": 43,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 58,
        "col": 47,
        "value": "T"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 48,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 58,
        "col": 49,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 58,
        "col": 55,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 58,
        "col": 59,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "253",
        "line": 58,
        "col": 60,
        "value": 253
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 58,
        "col": 63,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 58,
        "col": 64,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 58,
        "col": 65,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 58,
        "col": 69,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 58,
        "col": 70,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 58,
        "col": 71,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 58,
        "col": 72,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 58,
        "col": 73,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 58,
        "col": 77,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "238",
        "line": 58,
        "col": 78,
        "value": 238
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 58,
        "col": 81,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 58,
        "col": 82,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 58,
        "col": 83,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 58,
        "col": 87,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 58,
        "col": 88,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 58,
        "col": 89,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 58,
        "col": 90,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 58,
        "col": 91,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 58,
        "col": 95,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 58,
        "col": 96,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 58,
        "col": 98,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 58,
        "col": 99,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 58,
        "col": 100,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 58,
        "col": 104,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 58,
        "col": 105,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 58,
        "col": 106,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 58,
        "col": 107,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 108,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 58,
        "col": 109,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "tm",
        "line": 58,
        "col": 113,
        "value": "TM"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 58,
        "col": 115,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 58,
        "col": 116,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 58,
        "col": 118,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "50",
        "line": 58,
        "col": 121,
        "value": 50
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 123,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 58,
        "col": 124,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 128,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 58,
        "col": 129,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 58,
        "col": 133,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 58,
        "col": 134,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 58,
        "col": 138,
        "value": 2
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 58,
        "col": 139,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "590",
        "line": 59,
        "col": 1,
        "value": 590
    },
    {
        "type": "KEYWORD",
        "lexeme": "CLS",
        "line": 59,
        "col": 5,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 59,
        "col": 8,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 59,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 59,
        "col": 16,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 59,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 59,
        "col": 18,
        "value": 5
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 59,
        "col": 19,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 59,
        "col": 20,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Ha conseguido\"",
        "line": 59,
        "col": 25,
        "value": "Ha conseguido"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 59,
        "col": 40,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 59,
        "col": 41,
        "value": "PUNTOS"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 59,
        "col": 47,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"puntos.\"",
        "line": 59,
        "col": 48,
        "value": "puntos."
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 59,
        "col": 57,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "600",
        "line": 60,
        "col": 1,
        "value": 600
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 60,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 60,
        "col": 8,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": ">",
        "line": 60,
        "col": 14,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maxi",
        "line": 60,
        "col": 15,
        "value": "MAXI"
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 60,
        "col": 20,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "maxi",
        "line": 60,
        "col": 25,
        "value": "MAXI"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 60,
        "col": 29,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 60,
        "col": 30,
        "value": "PUNTOS"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 60,
        "col": 36,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 60,
        "col": 37,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 60,
        "col": 44,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 60,
        "col": 45,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 60,
        "col": 46,
        "value": 8
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 60,
        "col": 47,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 60,
        "col": 48,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"BATIO EL RECORD!!\"",
        "line": 60,
        "col": 53,
        "value": "BATIO EL RECORD!!"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 60,
        "col": 72,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 60,
        "col": 73,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "610",
        "line": 61,
        "col": 1,
        "value": 610
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 61,
        "col": 5,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 61,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 61,
        "col": 12,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 61,
        "col": 13,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 61,
        "col": 14,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 61,
        "col": 21,
        "value": 1
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 61,
        "col": 22,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "12",
        "line": 61,
        "col": 23,
        "value": 12
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 61,
        "col": 25,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 61,
        "col": 26,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"Pulse V para volver a empezar\"",
        "line": 61,
        "col": 31,
        "value": "Pulse V para volver a empezar"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 61,
        "col": 62,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 61,
        "col": 63,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "620",
        "line": 62,
        "col": 1,
        "value": 620
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 62,
        "col": 5,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 62,
        "col": 7,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INKEY$",
        "line": 62,
        "col": 8,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 62,
        "col": 14,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 62,
        "col": 15,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 62,
        "col": 18,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 62,
        "col": 20,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"v\"",
        "line": 62,
        "col": 21,
        "value": "v"
    },
    {
        "type": "OP",
        "lexeme": "OR",
        "line": 62,
        "col": 25,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a$",
        "line": 62,
        "col": 28,
        "value": "A$"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 62,
        "col": 30,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\"V\"",
        "line": 62,
        "col": 31,
        "value": "V"
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 62,
        "col": 35,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "630",
        "line": 62,
        "col": 40,
        "value": 630
    },
    {
        "type": "KEYWORD",
        "lexeme": "ELSE",
        "line": 62,
        "col": 44,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 62,
        "col": 49,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "620",
        "line": 62,
        "col": 54,
        "value": 620
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 62,
        "col": 57,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "630",
        "line": 63,
        "col": 1,
        "value": 630
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 63,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 63,
        "col": 9,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 10,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "MODE",
        "line": 63,
        "col": 11,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 63,
        "col": 16,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 17,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 63,
        "col": 18,
        "value": "X"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 63,
        "col": 19,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 63,
        "col": 20,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 21,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 63,
        "col": 22,
        "value": "Y"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 63,
        "col": 23,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 63,
        "col": 24,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 25,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 63,
        "col": 26,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 63,
        "col": 27,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 63,
        "col": 28,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 29,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 63,
        "col": 30,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 63,
        "col": 31,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 63,
        "col": 32,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 63,
        "col": 33,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 63,
        "col": 34,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "90",
        "line": 63,
        "col": 39,
        "value": 90
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 63,
        "col": 41,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "640",
        "line": 64,
        "col": 1,
        "value": 640
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 64,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 64,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "650",
        "line": 65,
        "col": 1,
        "value": 650
    },
    {
        "type": "COMMENT",
        "lexeme": "Edificio bombardeado",
        "line": 65,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 65,
        "col": 26,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "660",
        "line": 66,
        "col": 1,
        "value": 660
    },
    {
        "type": "COMMENT",
        "lexeme": "",
        "line": 66,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 66,
        "col": 6,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "670",
        "line": 67,
        "col": 1,
        "value": 670
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 67,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 67,
        "col": 12,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 67,
        "col": 14,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 67,
        "col": 15,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 67,
        "col": 16,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 17,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 67,
        "col": 18,
        "value": null
    },
    {
        "type": "STRING",
        "lexeme": "\" \"",
        "line": 67,
        "col": 23,
        "value": " "
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 26,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 67,
        "col": 27,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 31,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 67,
        "col": 32,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 33,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 67,
        "col": 34,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 35,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 67,
        "col": 36,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 67,
        "col": 40,
        "value": 4
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 41,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 67,
        "col": 42,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "tr",
        "line": 67,
        "col": 46,
        "value": "TR"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 67,
        "col": 48,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 67,
        "col": 49,
        "value": 1
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 67,
        "col": 51,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "INT",
        "line": 67,
        "col": 54,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 57,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "RND",
        "line": 67,
        "col": 58,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 61,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 67,
        "col": 62,
        "value": 1
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 63,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "*",
        "line": 67,
        "col": 64,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 67,
        "col": 65,
        "value": 3
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 66,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 67,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 67,
        "col": 68,
        "value": 1
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 69,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 67,
        "col": 70,
        "value": "PUNTOS"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 67,
        "col": 76,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 67,
        "col": 77,
        "value": "PUNTOS"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 83,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "5",
        "line": 67,
        "col": 85,
        "value": 5
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 86,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "SOUND",
        "line": 67,
        "col": 87,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "3",
        "line": 67,
        "col": 93,
        "value": 3
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 94,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4000",
        "line": 67,
        "col": 95,
        "value": 4000
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 99,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 67,
        "col": 100,
        "value": 10
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 102,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "12",
        "line": 67,
        "col": 103,
        "value": 12
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 105,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 67,
        "col": 106,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 107,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 67,
        "col": 108,
        "value": 0
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 109,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "10",
        "line": 67,
        "col": 110,
        "value": 10
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 112,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 67,
        "col": 113,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 67,
        "col": 120,
        "value": "A"
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 67,
        "col": 121,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 67,
        "col": 122,
        "value": "B"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 123,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "FOR",
        "line": 67,
        "col": 124,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "t",
        "line": 67,
        "col": 128,
        "value": "T"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 67,
        "col": 129,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 67,
        "col": 130,
        "value": 0
    },
    {
        "type": "KEYWORD",
        "lexeme": "TO",
        "line": 67,
        "col": 132,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 67,
        "col": 135,
        "value": 4
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 136,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 67,
        "col": 137,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 67,
        "col": 143,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 147,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "253",
        "line": 67,
        "col": 148,
        "value": 253
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 151,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 152,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 67,
        "col": 153,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 157,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 67,
        "col": 158,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 159,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 160,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 67,
        "col": 161,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 165,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "32",
        "line": 67,
        "col": 166,
        "value": 32
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 168,
        "value": null
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 169,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "CHR$",
        "line": 67,
        "col": 170,
        "value": null
    },
    {
        "type": "LPAREN",
        "lexeme": "(",
        "line": 67,
        "col": 174,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "8",
        "line": 67,
        "col": 175,
        "value": 8
    },
    {
        "type": "RPAREN",
        "lexeme": ")",
        "line": 67,
        "col": 176,
        "value": null
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 67,
        "col": 177,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 178,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 67,
        "col": 179,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 67,
        "col": 183,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 67,
        "col": 184,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 67,
        "col": 185,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 67,
        "col": 186,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "+",
        "line": 67,
        "col": 187,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 67,
        "col": 188,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 67,
        "col": 189,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "680",
        "line": 68,
        "col": 1,
        "value": 680
    },
    {
        "type": "KEYWORD",
        "lexeme": "IF",
        "line": 68,
        "col": 5,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 68,
        "col": 8,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 68,
        "col": 9,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "24",
        "line": 68,
        "col": 10,
        "value": 24
    },
    {
        "type": "KEYWORD",
        "lexeme": "THEN",
        "line": 68,
        "col": 13,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 68,
        "col": 18,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 68,
        "col": 19,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 68,
        "col": 20,
        "value": "B"
    },
    {
        "type": "OP",
        "lexeme": "-",
        "line": 68,
        "col": 21,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "1",
        "line": 68,
        "col": 22,
        "value": 1
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 68,
        "col": 23,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "690",
        "line": 69,
        "col": 1,
        "value": 690
    },
    {
        "type": "KEYWORD",
        "lexeme": "NEXT",
        "line": 69,
        "col": 5,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 69,
        "col": 9,
        "value": null
    },
    {
        "type": "LINE_NUMBER",
        "lexeme": "700",
        "line": 70,
        "col": 1,
        "value": 700
    },
    {
        "type": "KEYWORD",
        "lexeme": "LOCATE",
        "line": 70,
        "col": 5,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "7",
        "line": 70,
        "col": 12,
        "value": 7
    },
    {
        "type": "COMMA",
        "lexeme": ",",
        "line": 70,
        "col": 13,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "25",
        "line": 70,
        "col": 14,
        "value": 25
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 16,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 70,
        "col": 17,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "2",
        "line": 70,
        "col": 21,
        "value": 2
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 22,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PRINT",
        "line": 70,
        "col": 23,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "puntos",
        "line": 70,
        "col": 29,
        "value": "PUNTOS"
    },
    {
        "type": "SEMICOLON",
        "lexeme": ";",
        "line": 70,
        "col": 35,
        "value": null
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 36,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "cae",
        "line": 70,
        "col": 37,
        "value": "CAE"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 70,
        "col": 40,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "0",
        "line": 70,
        "col": 41,
        "value": 0
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 42,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "a",
        "line": 70,
        "col": 43,
        "value": "A"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 70,
        "col": 44,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "x",
        "line": 70,
        "col": 45,
        "value": "X"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 46,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "b",
        "line": 70,
        "col": 47,
        "value": "B"
    },
    {
        "type": "COMP",
        "lexeme": "=",
        "line": 70,
        "col": 48,
        "value": null
    },
    {
        "type": "IDENT",
        "lexeme": "y",
        "line": 70,
        "col": 49,
        "value": "Y"
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 50,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "PEN",
        "line": 70,
        "col": 51,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "4",
        "line": 70,
        "col": 55,
        "value": 4
    },
    {
        "type": "COLON",
        "lexeme": ":",
        "line": 70,
        "col": 56,
        "value": null
    },
    {
        "type": "KEYWORD",
        "lexeme": "GOTO",
        "line": 70,
        "col": 57,
        "value": null
    },
    {
        "type": "INT",
        "lexeme": "230",
        "line": 70,
        "col": 62,
        "value": 230
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 70,
        "col": 65,
        "value": null
    },
    {
        "type": "EOL",
        "lexeme": "\\n",
        "line": 71,
        "col": 33,
        "value": null
    },
    {
        "type": "EOF",
        "lexeme": "",
        "line": 72,
        "col": 1,
        "value": null
    }
]