///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/molusk.aks
/// Generation time: Wed Oct  4 18:08:16 CEST 2023
///

/// Song 'molusk_song' metadata macros
#define molusk_song_address  0x1D4D
#define molusk_song_size     8883
#define molusk_song_end      0x3fff

/// Song 'molusk_song' array declaration
extern void molusk_song[molusk_song_size];
