"""
From CPCWiki:
https://www.cpcwiki.eu/index.php/Locomotive_BASIC

BASIC 1.0 (officially) describes error codes until 30 (without an attached floppy disc controller). 31 & 32 are floppy disc error codes.

Table of ERRor codes:

========================================================================================
| VALUE | NAME                    | DESCRIPTION                                        |
========================================================================================
|   1   |Unexpected NEXT          |A NEXT command has been encountered while not in a  |
|       |                         |FOR loop, or the control variable in the NEXT       |
|       |                         |command does not match that in the FOR.             |
|   2   |Syntax Error             |BASIC cannot understand the given line because      |
|       |                         |a construct within it is not legal.                 |
|   3   |Unexpected RETURN        |A RETURN command has been encountered when not in a |
|       |                         |subroutine.                                         |
|   4   |DATA exhausted           |A READ command has attempted to read beyond the end |
|       |                         |of the last DATA.                                   |
|   5   |Improper Argument        |This is a general purpose error. The value of a     |
|       |                         |function's argument, or a command parameter is      |
|       |                         |invalid in some way.                                |
|   6   |Overflow                 |The result of an arithmetic operation has over-     |
|       |                         |flowed. This may be a floating point overflow, in   |
|       |                         |which case some operation has yielded a value       |
|       |                         |greater than 1.7E^38 (approx.). Alternatively, this |
|       |                         |may be the result of a failed attempt to change a   |
|       |                         |floating point number to a 16 bit signed integer.   |
|   7   |Memory full              |The current program or its variables may be simply  |
|       |                         |too big, or the control structure is too deeply     |
|       |                         |nested (nested GOUSBs, WHILEs or FORs).             |
|       |                         |A MEMORY command will give this error if an attempt |
|       |                         |is made to set the top of BASIC's memory too low, or|
|       |                         |to an impossible high value. Note that an open file |
|       |                         |has a buffer allocated to it, and that may restrict |
|       |                         |the values that MEMORY may use.                     |
|   8   |Line does not exist      |The line referenced cannot be found.                |
|   9   |Subcript out of range    |One of the subscripts in an array reference is too  |
|       |                         |big or too small.                                   |
|  10   |Array already dimensioned|One of the arrays in a DIM statement has already    |
|       |                         |been declared.                                      |
|  11   |Division by zero         |May occur in real division, integer division,       |
|       |                         |integer modulus or exponentiation.                  |
|  12   |Invalid direct command   |The last command attempted is not valid in direct   |
|       |                         |mode.                                               |
|  13   |Type mismatch            |A numeric value has been presented where a string   |
|       |                         |value is required or vice versa, or an invalidly    |
|       |                         |formed number has been found in READ or INPUT.      |
|  14   |String space full        |So many strings have been created that there is no  |
|       |                         |further room available, even after 'garbage         |
|       |                         |collection'.                                        |
|  15   |String too long          |Strings exceeds 255 characters in length. May be    |
|       |                         |generated by appending strings together.            |
|  16   |String expression too    |String expressions may generate a number of         |
|       |complex                  |intermediate string values. When the number of these|
|       |                         |values exceeds a reasonable limit, this error       |
|       |                         |results.                                            |
|  17   |Cannot CONTinue          |For one reason or another the current program       |
|       |                         |be restarted using CONT. Note that CONT is intended |
|       |                         |for restarting after a STOP command, [ESC][ESC],    |
|       |                         |or an error, and that any alteration of the         |
|       |                         |program in the meantime makes a restart impossible. |
|  18   |Unknown user function    |No DEF FN has been executed for the FN just         |
|       |                         |invoked.                                            |
|  19   |RESUME missing           |The end of the program has been encountered while   |
|       |                         |in error processing mode (i.e. in an ON ERROR GOTO  |
|       |                         |routine).                                           |
|  20   |Unexpected RESUME        |RESUME is only valid while in error processing mode |
|       |                         |(i.e. in an ON ERROR GOTO routine).                 |
|  21   |Direct command found     |When loading a file, a line without a line number   |
|       |                         |has been found.                                     |
|  22   |Operand missing          |BASIC has encountered an incomplete expression.     |
|  23   |Line too long            |A line when converted to BASIC internal-form becomes|
|       |                         |too big.                                            |
|  24   |EOF met                  |An attempt has been made to read past end of the    |
|       |                         |file input stream.                                  |
|  25   |File type error          |The file being read is not of a suitable type.      |
|       |                         |OPENIN is only prepared to open ASCII text files.   |
|       |                         |Similarly, LOAD, RUN, etc, are only prepared to     |
|       |                         |deal with file types produces by SAVE.              |
|  26   |NEXT missing             |Cannot find a NEXT to match a FOR command. A line   |
|       |                         |number accompanying this message indicates the FOR  |
|       |                         |command to which this error applies.                |
|  27   |File already open        |An OPENIN or OPENOUT command has been executed      |
|       |                         |before the previously opened file has been closed.  |
|  28   |Unknown command          |BASIC cannot find a taker for an external command,  |
|       |                         |i.e. a command preceded by a bar |.                 |
|  29   |WEND missing             |Cannot find a WEND to match a WHILE command.        |
|  30   |Unexpected WEND          |Encountered a WEND when not in a WHILE loop, or a   |
|       |                         |WEND that does not match the current WHILE loop.    |
|  31   |File not open            |(see 'Disc ERRors above).                           |
|       |                         |If access attempted when no file was open.          |
|  32   |Broken in                |(see 'Disc ERRors above).                           |
|       |                         |If access attempted when no file was open.          |
|       |                         |                                                    |
|       |                         |If value 31 or 32 are stated, DERR could be         |
|       |                         |interrogate to give more detailed information.      |
|       |                         |(see example below.)                                |
========================================================================================

"""

from __future__ import annotations
import os
from enum import Enum
os.system("")  # enables ansi escape characters in terminal

TERM = {
    "HEADER": "\033[95m",
    "BLUE": "\033[94m",
    "GREEN": "\033[92m",
    "RED": "\033[91m",
    "UNDER": "\033[4m",
    "END": "\033[0m",
}

_ERRORCODES = {
    """ 
    Not all errorcodes are used as several of them were designed for an
    interpreter a not for a compiler
    """
    # -------- Original error codes used by BASIC interpreter ---------
    "001": "Unexpected NEXT",
    "002": "Syntax Error",
    "003": "Unexpected RETURN",
    "004": "DATA exhausted",
    "005": "Improper Argument",
    "006": "Overflow",
    "007": "Memory full",
    "008": "Line does not exist",
    "009": "Subcript out of range",
    "010": "Array already dimensioned",
    "011": "Division by zero",
    "012": "Invalid direct command",
    "013": "Type mismatch",
    "014": "String space full",
    "015": "String too long",
    "016": "String expression too complex",
    "017": "Cannot CONTinue",
    "018": "Unknown user function",
    "019": "RESUME missing",
    "020": "Unexpected RESUME",
    "021": "Direct command found",
    "022": "Operand missing",
    "023": "Line too long",
    "024": "EOF met",
    "025": "File error",
    "026": "NEXT missing",
    "027": "File already open",
    "028": "Unknown command",
    "029": "WEND missing",
    "030": "Unexpected WEND",
    "031": "File not open",
    "032": "Broken in",
    # -------- Custom error codes used by ABASC ---------
    "033": "File doesn't exist",
    "034": "Line number already exists",
    "035": "END IF missing",
    "036": "Unexpected END IF",
    "037": "Unexpected ELSE",
    "038": "Undefined identifier",
    "039": "Label already defined",
    "040": "Variable already defined",
    "041": "Unexpected END SUB",
    "042": "END SUB missing",
    "043": "Unexpected END FUNCTION",
    "044": "END FUNCTION missing",
    "045": "END SELECT missing",
    "046": "Unexpected END SELECT",
}

class BasError(Exception):
    def __init__(self, ecode: int, source: str = "", code: str = "", line: int = -1, col: int = -1, info: str = "") -> None:
        self.ecode = f"{ecode:03d}"
        self.source = source
        self.code = code
        self.line = line
        self.col = col
        self.info = info

    def __str__(self) -> str:
        msg = f"[ERR{self.ecode}] "
        if self.source != "":
            msg = msg + f"{self.source}"
            msg = msg + (f":{self.line}" if self.line != -1 else "")
            msg = msg + (f":{self.col} " if self.col != -1 else " ")
        msg = msg + f"{_ERRORCODES[self.ecode]} "
        msg = msg + (f"({self.info}) " if self.info != "" else "")
        code = self.code
        if code != "" and self.col != -1:
            code = code[:self.col-1] + TERM["UNDER"] + code[self.col-1:] + TERM["END"]
        msg = msg + (f"in {code}" if code != "" else "")
        return msg

class WarningLevel(int, Enum):
    NONE     = 0,
    HIGH     = 1,
    MEDIUM   = 2,
    LOW      = 3,
    ALL      = 4