"""
Translates intermediate code generated by the parser
to Amstrad CPC Z80 Assembly language in Maxam/WinAPE style.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation in its version 3.

This program is distributed in the hope that it will be useful
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
"""

from __future__ import annotations
from typing import List, Optional, cast
from baspp import CodeLine
from baserror import BasError
from symbols import SymTable, SymEntry, SymType
import astlib as AST

class z80Emitter:
    def __init__(self, code: list[CodeLine], program: AST.Program, symtable: SymTable, warning_level=-1):
        self.code = code
        self.program = program
        self.symtable = symtable
        self.warning_level = warning_level
        self.asm = ""

    def _emit_asm(self, line: str):
        line = line + '\n'
        self.asm = self.asm + line

    def _emit_head(self):
        pass

    def _emit_data(self):
        pass

    # ----------------- Error management -----------------

    def _raise_error(self, codenum: int, node: AST.ASTNode, info: str = ""):
        codeline = self.code[node.line - 1]
        raise BasError(
            codenum,
            codeline.source,
            codeline.code,
            codeline.line,
            node.col,
            info
        ) 

    def _raise_warning(self, level: int, msg: str, node: AST.ASTNode):
        if self.warning_level < 0 or self.warning_level >= level:
            # tokens start line counting in 1
            codeline = self.code[node.line - 1]
            print(f"[WARNING] {codeline.source}:{codeline.line}:{node.col}: {msg} in {codeline.code}")

    # ----------------- Commands and Functions -----------------

    def _emit_ABS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_AFTER(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ASC(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ATN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_AUTO(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_BINSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_BORDER(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CALL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CAT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CHAIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CHAIN_MERGE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CHRSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CINT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CLEAR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CLEAR_INPUT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CLG(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CLOSEIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CLOSEOUT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CLS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CONT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_COPYCHRSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_COS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CREAL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_CURSOR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DATA(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DECSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DEF(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DEFINT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DEFREAL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DEFSTR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DEF_FN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DEG(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DELETE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DERR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DI(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DIM(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DRAW(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_DRAWR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_EDIT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_EI(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ELSE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_END(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ENT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ENV(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_EOF(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ERASE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ERL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ERR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ERROR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_EVERY(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_EXP(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_FILL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_FIX(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_FN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_FOR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_FRAME(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_FRE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_GOSUB(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_GOTO(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_GRAPHICS_PAPER(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_GRAPHICS_PEN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_HEXSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_HIMEM(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_IF(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_IFEND(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INK(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INKEY(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INKEYSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INP(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INPUT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INSTR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_INT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_JOY(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_KEY(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_KEY_DEF(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LEFTSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LEN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LET(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LINE_INPUT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LIST(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LOAD(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LOCATE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LOG(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LOG10(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_LOWERSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MASK(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MAX(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MEMORY(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MERGE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MIDSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MODE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MOVE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_MOVER(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_NEW(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_NEXT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ON(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ON_BREAK(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ON_ERROR_GOTO(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ON_SQ(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_OPENIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_OPENOUT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ORIGIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_OUT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PAPER(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PEEK(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PEN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PI(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PLOT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PLOTR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_POKE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_POS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_PRINT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RAD(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RANDOMIZE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_READ(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RELEASE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_REMAIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RENUM(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RESTORE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RESUME(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RETURN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RIGHTSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RND(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ROUND(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_RUN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SAVE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SGN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SIN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SOUND(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SPACESS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SPC(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SPEED_INK(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SPEED_KEY(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SPEED_WRITE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SQ(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SQR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_STOP(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_STRINGSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_STRSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SYMBOL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_SYMBOL_AFTER(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TAB(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TAG(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TAGOFF(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TAN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TEST(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TESTR(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_THEN(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TIME(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TROFF(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_TRON(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_UNT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_UPPERSS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_VAL(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_VPOS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WAIT(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WEND(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WHILE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WIDTH(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WINDOW(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WINDOW_SWAP(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_WRITE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_XPOS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_YPOS(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    def _emit_ZONE(self, node:AST.Statement):
        self._raise_error(2, node, 'not implemented yet')

    # ----------------- Expressions -----------------


    # ----------------- AST Trasversal functionsr -----------------

    def _emit_comment(self, node: AST.Comment):
        self._emit_asm(f"; {node.text}")

    def _emit_assigment(self, node: AST.Assignment):
        self._raise_error(2, node, "not implemented yet")

    def _emit_blockend(self, node: AST.BlockEnd):
        self._raise_error(2, node, "not implemented yet")

    def _emit_userfun(self, node: AST.UserFun):
        self._raise_error(2, node, "not implemented yet")

    def _emit_function(self, node: AST.Function):
        keyword = node.name
        funcname = "_emit_" + keyword.replace('$','SS').replace(' ', '_')
        emit_keyword = getattr(self, funcname , None)
        if emit_keyword is None:
            self._raise_error(2, node, f", unknown keyword {keyword}")
        return emit_keyword(node) # type: ignore[misc]

    def _emit_command(self, node: AST.Command):
        keyword = node.name
        funcname = "_emit_" + keyword.replace('$','SS').replace(' ', '_')
        emit_keyword = getattr(self, funcname , None)
        if emit_keyword is None:
            self._raise_error(2, node, f", unknown keyword {keyword}")
        return emit_keyword(node) # type: ignore[misc]

    def _emit_statement(self, stmt: AST.Statement):
        if isinstance(stmt, AST.Comment):
            self._emit_comment(stmt)
        elif isinstance(stmt, AST.Assignment):
            self._emit_assigment(stmt)
        elif isinstance(stmt, AST.If):
            self._emit_IF(stmt)
        elif isinstance(stmt, AST.ForLoop):
            self._emit_FOR(stmt)
        elif isinstance(stmt, AST.WhileLoop):
            self._emit_WHILE(stmt)
        elif isinstance(stmt, AST.BlockEnd):
            self._emit_blockend(stmt)
        elif isinstance(stmt, AST.Print):
            self._emit_PRINT(stmt)
        elif isinstance(stmt, AST.Input):
            self._emit_INPUT(stmt)
        elif isinstance(stmt, AST.LineInput):
            self._emit_LINE_INPUT(stmt)
        elif isinstance(stmt, AST.Write):
            self._emit_WRITE(stmt)
        elif isinstance(stmt, AST.DefFN):
            self._emit_DEF_FN(stmt)
        elif isinstance(stmt, AST.UserFun):
            self._emit_userfun(stmt)
        elif isinstance(stmt, AST.Function):
            self._emit_function(stmt)
        elif isinstance(stmt, AST.Command):
            self._emit_command(stmt)
        else:
            self._raise_error(2, stmt, "unexpected statement")

    def _emit_line(self, line: AST.Line):
        for stmt in line.statements:
            self._emit_statement(stmt)

    def emit_program(self) -> str:
        self.asm = ""
        self._emit_head()
        for line in self.program.lines:
            self._emit_line(line)
        self._emit_data()
        return self.asm