; Data created with Img2CPC - (c) Retroworks - 2007-2017
; Tile g_building_1: 22x125 pixels, 11x125 bytes.
g_building_1: ; 11 * 125 bytes
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &ff, &ff, &f3, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &ff, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &03, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &03, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &ff, &ff, &f3, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &ff, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &03, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &ff, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &03, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &03, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &f3, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &f3, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &f3, &ff, &ff, &ff, &ff, &ff
