; Data created with Img2CPC - (c) Retroworks - 2007-2017
; Tile g_building_3: 18x80 pixels, 9x80 bytes.
g_building_3: ; 9 * 80 bytes
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &03, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &03, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &ff, &ff, &33, &ff, &f3, &ff
	db &ff, &f3, &ff, &ff, &ff, &33, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &03, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &03, &ff, &f3, &ff, &33, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &ff, &ff, &33, &ff, &f3, &ff
	db &ff, &f3, &ff, &ff, &ff, &33, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &f3, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &ff, &ff
	db &ff, &f3, &ff, &f3, &ff, &03, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &33, &ff, &f3, &ff, &f3, &ff, &f3, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &f3, &ff, &ff, &ff, &f3, &ff
	db &ff, &ff, &ff, &f3, &ff, &ff, &ff, &f3, &ff
	db &ff, &ff, &ff, &f3, &ff, &ff, &ff, &f3, &ff
