; Data created with Img2CPC - (c) Retroworks - 2007-2017
; Tile g_building_2: 14x103 pixels, 7x103 bytes.
g_building_2: ; 7 * 103 bytes
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ab, &57, &ff, &fb, &f7, &ff
	db &ff, &ab, &57, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ab, &57, &ff, &fb, &f7, &ff
	db &ff, &ab, &57, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &ab, &57, &ff
	db &ff, &fb, &f7, &ff, &ab, &57, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &bb, &77, &ff, &fb, &f7, &ff
	db &ff, &bb, &77, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ab, &57, &ff, &fb, &f7, &ff
	db &ff, &ab, &57, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &fb, &f7, &ff, &bb, &77, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ab, &57, &ff, &ff, &ff, &ff
	db &ff, &ab, &57, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &fb, &f7, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &fb, &f7, &ff, &ab, &57, &ff
	db &ff, &fb, &f7, &ff, &ab, &57, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &bb, &77, &ff, &fb, &f7, &ff
	db &ff, &bb, &77, &ff, &fb, &f7, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
	db &ff, &ff, &ff, &f3, &ff, &ff, &ff
	db &ff, &ff, &ff, &f3, &ff, &ff, &ff
	db &ff, &ff, &ff, &f3, &ff, &ff, &ff
	db &ff, &ff, &ff, &ff, &ff, &ff, &ff
